### ISSUE TITLE
python rawclinet batch put meet exception

### ISSUE THREAD

**Issue by RunziiMo** [tikv/client-py#6]
Here is my code
```
pairs = {}
for record in r['records']:
    rowkey = urllib.parse.unquote(record['rowkey'])
    for features in record['columns']:
        if features['name'] == columns:
            features = urllib.parse.unquote(features['value'])
            # pairs[rowkey.encode()] = features.encode()
            pairs[b'123'] = b'456'
for key, value in pairs.items():
    print(key, len(value))
client.batch_put(pairs)
```
then I got exception like this:
```
Traceback (most recent call last):
  File "test_tikv.py", line 69, in <module>
    func(*sys.argv[2:])
  File "test_tikv.py", line 36, in sync
    client.batch_put(pairs)
  File "/home/work/.jumbo/lib/python3.6/site-packages/tikv_client/__init__.py", line 33, in batch_put
    event_loop.run_until_complete(self.inner.put(pairs, cf))
TypeError: Can't convert {b'123': b'456'} to Sequence
```

do you guys have a more specific examples?

**Comment by andylokandy** [comment]
I think it's a bug and I've been investigating for a while it but met problems on rust client, so it may take some time.
